### ISSUE TITLE
review changes - Feature request

### ISSUE THREAD

**Issue by amicaross** [cerebrate-project/cerebrate#125]
Ability to see a list of all changes made to users in a selectable period of time (Start data, end Date).
Ability to export in csv (xls)

Priority: High/Blocking
Note: Sent via email to CIRCL om 30/01/2023 - here for status update

Crucial issue for auditing day to day operations.

**Comment by mokaddem** [comment]
The list of all the changes is already available by using the audit log system (`/auditLogs/index`)
However, some improvements on the filtering and UX aspects have been done:
- e9056a7b4ce5c54cab112b8bd5bf274b56e522bf: Support of multiple filtering options
![image](https://user-images.githubusercontent.com/6977223/222365716-f1c6e17b-f634-4a3a-866e-411060934577.png)

- 62b2a1b2647e7651bc7f8486311e232686ae8804: Added quick view for selected entity
![image](https://user-images.githubusercontent.com/6977223/222366161-41c8dc7b-b00c-4f12-b783-9591e9923aaf.png)

Export to CSV is currently considered out of scope as JSON export is already functional and there are easy way to transform JSON to CSV (JQ or mapping via scripting)
