### ISSUE TITLE
Improve readability of detailed information - Feature request

### ISSUE THREAD

**Issue by amicaross** [cerebrate-project/cerebrate#127]
Messages > Inbox  >  Notifications: detailed information is in json format
Priority: High/Blocking
Note: Sent via email to CIRCL om 30/01/2023 - here for status update
Notifications data is in json, challenging for a human to read the data and follow all changes.
Reduces usability for managing large numbers of users

**Comment by mokaddem** [comment]
Interface has been improved to ease readability in 881e1168893deba2f769e36d6111327dc41cc6f1
![image](https://user-images.githubusercontent.com/6977223/222368183-6213108b-9b24-404d-aa61-5b78dc1ad3b0.png)
