### ISSUE TITLE
Issues when adding new or updating Meta Field Templates - Bug report

### ISSUE THREAD

**Issue by amicaross** [cerebrate-project/cerebrate#128]
Issues when adding new or updating Meta Field Templates by editing the definition (json file)
Priority: High/Blocking
Note: Sent via email to CIRCL om 23/01/2023 - here for status update

Need to be able to easily make changes to template and the settings to be easily transferred from one version to the next.

**Comment by iglocska** [comment]
This has been addressed by the latest release with a built in tool developed by @mokaddem allowing for various update/merge strategies.
