### ISSUE TITLE
Development roadmap - Tracking issue

### ISSUE THREAD

**Issue by amicaross** [cerebrate-project/cerebrate#130]
Priority: High/Blocking
Note: Sent via email to CIRCL om 30/01/2023 - here for status update
We need a clear roadmap for cerebrate with milestones and features in the planned future releases

**Comment by iglocska** [comment]
The roadmap of Cerebrate is in flux, similarly to our development of MISP, we will mostly stick to an approach where we have a larger bucket of features / improvements that we are planning on doing and a stricter short term roadmap. 

What will influence the roadmap are:
- immediate requests for improvements
- longer term projects / collaborations that fund our development efforts
- requirements from the various sectorial / regional user groups

Our current immediate roadmap is one of consolidation:
- fix reported issues
- flesh out some of the more half-baked functionalities already present

Some of the items on our more near term "bucket":
- sharing group blueprints / inheritance from MISP
- mailing integration
- Individual/organisation capability taxonomies
- Rework of the codebase in terms of extracting shared parts with the upcoming MISP version into separate submodules

**Comment by adulau** [comment]
The roadmap is now on the website https://www.cerebrate-project.org/roadmap.html which can vary depending of the organisations and sector will to have some changes.
