### ISSUE TITLE
Issues with Web interface when using the dark theme - Bug report

### ISSUE THREAD

**Issue by amicaross** [cerebrate-project/cerebrate#135]
Priority: Low
Note: Sent via email to CIRCL om 30/01/2023 - here for status update 
Mailing lists - while using the adding user to the list, the filed is white, values only show one mouse is over. Same issue with adding individuals to certain organizations.

**Comment by mokaddem** [comment]
Could you provide a screenshot of this issue? It's working fine on mine
![image](https://user-images.githubusercontent.com/6977223/222370607-b07309e0-91b8-40c2-abef-156813553c12.png)

**Comment by mokaddem** [comment]
Should be mitigated with db19afd9ac9b6f86e3b2eb0e70c6bc4476b284b8 until we introduce the generation of select2's CSS file into the scss generation pipeline.
Closing the issue for now. Please re-open or provide feedback if you still encounter the issue!
