### ISSUE TITLE
Creation of organizations: tootip - Feature request

### ISSUE THREAD

**Issue by amicaross** [cerebrate-project/cerebrate#136]
Priority: Low
Note: Sent via email to CIRCL om 30/01/2023 - here for status update 
Need tooltip for UUID, to tell that MISP UUID should be used if possible

**Comment by mokaddem** [comment]
Fixed in 22c460575eea8bc9d93a549ed20763b48138720d
![image](https://user-images.githubusercontent.com/6977223/222370934-65dbd077-0c54-4a33-bfb4-ad498f680c6d.png)
