### ISSUE TITLE
Creation of organisations: Nationality - Bug report

### ISSUE THREAD

**Issue by amicaross** [cerebrate-project/cerebrate#139]
Priority: Low
Note: Sent via email to CIRCL om 30/01/2023 - here for status update 
Nationality field is filled with country names, misleading title (put country instead)

**Comment by iglocska** [comment]
Partially fixed via: 
https://github.com/cerebrate-project/cerebrate/commit/ab2ab4e8f8233e82e567f1d60697f4cbb5fd3518

The display has changed to country, however internally, via the API and via the filtering functionalities the field is still called nationality. This might change in the future, but MISP has historically always called it "nationality" - meaning that we'd end up with a diverging organisation data model.
