### ISSUE TITLE
Creation of organisations: Filter operators - Feature request

### ISSUE THREAD

**Issue by amicaross** [cerebrate-project/cerebrate#141]
Priority: Low
Note: Sent via email to CIRCL om 30/01/2023 - here for status update 
Filter operators = and != are too few. We need "like" too (search for fraction of text)

**Comment by iglocska** [comment]
It is not documented in the widget, but you can already do this. The value field accepts SQL wildcard operators, so if you wanted to search for any organisation containing the term "CIRCL" you could seach via "%CIRCL%".

**Comment by iglocska** [comment]
My bad, I was wrong about it not being documented, the value field explains this when hovering over it.
