### ISSUE TITLE
"Error while loading the processor" for role button - Bug report

### ISSUE THREAD

**Issue by amicaross** [cerebrate-project/cerebrate#142]
Priority: Low
Add Role button is visible to users with Team/Standing Representative role. When Clicked it throws an error. "Error while loading the processor". Can the button be visible depending on the role permission? (Remove Add role button)

**Comment by mokaddem** [comment]
Nice catch! Fixed in a67c6b70d538adb0d12723a3f48ccd6cc7bbe2b2
