### ISSUE TITLE
A Team Representative, can add users with email that belongs to another organisation  - Bug report

### ISSUE THREAD

**Issue by amicaross** [cerebrate-project/cerebrate#143]
Priority: Low
A Team representative from ORG-A (e.g. user@org-a ) should not be able to add users with an email that belongs to ORG-B domain (e.g. user@org-b)

**Comment by iglocska** [comment]
This is somewhat tricky to enforce as domains are not directly tied to an organisation. For example, certain teams might have multiple domains used for e-mail addresses (in the case of CIRCL, it could be @lhc.lu for example). 

Either way, the potential impact would be a team-rep disclosing their own organisation to a third party, so the potential damage with misuse is simply self-harm.

However, please feel free to re-open the issue if you see any other potential issues / solutions with this.
