### ISSUE TITLE
When adding an authentication key for a user: User selection - Feature request

### ISSUE THREAD

**Issue by amicaross** [cerebrate-project/cerebrate#146]
Priority: Low
Can the user drop down be limited to the current user we are editing/showing?
Or can the default value be empty, if an admin is not careful they might add a key to a different user. 
Can the users be searchable and not a drop down?

**Comment by mokaddem** [comment]
Good point. Current logged-in user is selected by default (487670e522b5fbbe7b631305181ca64d75e32dfb)
