### ISSUE TITLE
Bug: Not having a proxy set, is considered a critical issue in settings diagnostics

### ISSUE THREAD

**Issue by Wachizungu** [cerebrate-project/cerebrate#176]
## Actual behavior
Not having a proxy set, is considered a critical issue in settings diagnostic

## Expected behavior
Not having a proxy set, is not considered an issue

## Reproduction scenario
Do not configure any proxy, go <base_url>/instance/settings

## Version
1.25 (e8f5165)

## Extra info
![image](https://github.com/user-attachments/assets/eeed9998-8ead-4b68-9522-b59e8cdb86c8)

**Comment by iglocska** [comment]
That's dumb, nice catch.
