### ISSUE TITLE
Bug: Can't create role with community admin permission

### ISSUE THREAD

**Issue by Wachizungu** [cerebrate-project/cerebrate#179]
## Actual behavior
The community admin permission is unset, even when the related checkbox is checked on creation / edit of the role.

## Expected behavior
The community admin permission is set, when the checkbox is checked on creation / edit of the role.

## Reproduction scenario
Create a new role, check the 'Community admin' checkbox, click Confirm. -> new role doesn't have community admin.
Same thing on edit.

Version
1.25 (e8f5165b111c12b27a212d73d0cddd229aac862e)

**Comment by iglocska** [comment]
This sounds like an update gone wrong, could you try clearing the model caches?

**Comment by Wachizungu** [comment]
Just ran these commands:

sudo rm /var/www/cerebrate/tmp/cache/models/*
sudo rm /var/www/cerebrate/tmp/cache/persistent/*

If there's anything else I can check/run let me know. This is on a fresh install, following https://doc.cerebrate-project.org/install/#cerebrate-installation-instructions
