### ISSUE TITLE
Bug: [cosmetic] Trying to delete a role which has an associated user leads to internal server error

### ISSUE THREAD

**Issue by Wachizungu** [cerebrate-project/cerebrate#180]
## Actual behavior
Trying to delete a role which has an associated user leads to internal server error

## Expected behavior
Trying to delete a role which has an associated user leads to clean error message, noting you can't delete a role which has associated users.

## Reproduction scenario
Create a new test role, assign it to a user, then attempt to delete the role.

## Version
1.25 (e8f5165b111c12b27a212d73d0cddd229aac862e)

Extra info
![image](https://github.com/user-attachments/assets/33bbe848-3a92-4b8b-adbf-ba1bd6f838a7)

**Comment by iglocska** [comment]
The fix explains the error (and checks before throwing it at the DB):

![image](https://github.com/user-attachments/assets/bb3ed8ef-dc82-432b-8e0c-1afdcb76592e)
