### ISSUE TITLE
Error editing user: "You cannot assign the chosen organisation"

### ISSUE THREAD

**Issue by INCIBE-CERT** [cerebrate-project/cerebrate#198]
Steps to reproduce:
* Visit /users/index
* Choose a team member and select the edit option
* Optionally change something
* Press confirm

Expected result:
* It saves the changes

Actual result:
* It fails with the message "Custom checks: You cannot assign the chosen organisation to a user."
* It turns out the post to /users/edit/<id> returned
```
{
    "success": false,
    "message": "Could not save User.",
    "errors": {
        "Custom checks": {
            "Custom checks": "You cannot assign the chosen organisation to a user."
        }
    },
    "description": "",
    "url": ""
}
```

This happens across multiple users. No special characters involved. The edit user form doesn't contain an Org field, even.

**Comment by iglocska** [comment]
Hmm that definitely sounds like a bug, the edit shouldn't trigger that check at all if the org hasn't been changed.

**Comment by iglocska** [comment]
Thanks for the heads-up, was indeed an over-eager validation gone wrong, it should be fixed now!

**Comment by INCIBE-CERT** [comment]
Great!
