### ISSUE TITLE
TODO: Flexible key-value in user settings to extend the fields in organisation, users

### ISSUE THREAD

**Issue by adulau** [cerebrate-project/cerebrate#20]
TODO: Flexible key-value in user settings to extend the fields in organisation, users

**Comment by adulau** [comment]
Additional meta fields to recommend to define scope and constituency of an organisation:

- ASNs (decimal value) - 6661
- Domains (string) - circl.lu
- IP Ranges (CIDR blocks in v4 or v6) - 149.13.33.0/25
- Country code (ISO 3166-1 alpha-3 or alpha-2 - not consistent across TF-CSIRT/FIRST) - LU / LUX

The domain string can be challenging because it can be composed in string like:

- lu
- *.lu

(example: https://www.trusted-introducer.org/directory/teams/circl.html)

**Comment by iglocska** [comment]
Implemented via vocabularies.

**Comment by adulau** [comment]
Thanks a lot! This is cool.
