### ISSUE TITLE
Networking requirements

### ISSUE THREAD

**Issue by wagner-certat** [cerebrate-project/cerebrate#43]
Does Cerebrate need any specific networking set-ups? I guess it needs access to the MISP instance (which is mentioned in https://github.com/cerebrate-project/cerebrate/wiki/CLI-Tools-usage#user-content-importing-new-data-from-a-misp-instance), possibly in the future as well to IntelMQ. Does it need to be publicly reachable?

**Comment by iglocska** [comment]
It doesn't need to be publicly reachable unless you want to act as a hub for other cerebrates / tools. Other than that it so far only needs port 80/443 depending on your setup.

**Comment by wagner-certat** [comment]
> It doesn't need to be publicly reachable unless you want to act as a hub for other cerebrates / tools.

:+1: 

> Other than that it so far only needs port 80/443 depending on your setup.

I guess you mean port 8000 (according to the install docs)?

**Comment by iglocska** [comment]
That's an example setup, I'd fully expect operational deployments to purely use 80/443.

**Comment by wagner-certat** [comment]
> That's an example setup, I'd fully expect operational deployments to purely use 80/443.

But the apache config from the install docs (INSTALL/cerebrate_dev.conf) uses port 8000, so it needs to be changed to port 80 there.

**Comment by iglocska** [comment]
That is an example conf file to be modified by whoever is installing Cerebrate. Your choice of port will depend on whether you directly expose cerebrate in a dmz for example (443 is preferred in most cases then), behind a reverse proxy that terminates ssl at the boundary (80 normally in this case) or in a VM for development/testing (often a high port used for convenience such as 8000). 

Also, we do not define certificates, servername, etc in the conf, it's definitely something for the sysadmins to modify.

**Comment by wagner-certat** [comment]
Thanks for the insight.

Do you know what I thought about that port 8000, weeks ago before we started the installation? I assumed that port 8000 was chosen on purpose by you, for example as it is an internal interface, and port 80 is (or will be) used for another interface of cerebrate. From my perspective as a uninformed user, I do not know your expectations, assumptions and plans.

btw:

> Create an apache config file for cerebrate / ssh key and point the document root to /var/www/cerebrate/webroot and you're good to go

what is that ssh key to be used for?

**Comment by iglocska** [comment]
That's a brainfart, should be ssl / tls :)

**Comment by wagner-certat** [comment]
Solved by https://github.com/cerebrate-project/cerebrate/commit/66f9f85ed02750121031c5721fdfe1fad9f30d3d
