### ISSUE TITLE
Edit link on /users/index leads to homepage

### ISSUE THREAD

**Issue by wagner-certat** [cerebrate-project/cerebrate#46]
The edit-action button for a user links to `example.com#` instead of opening the modal dialog.

The HTML code of the button looks like:
```
<a href="http://cerebrate.intern.cert.at:8000#" title="" aria-label="" onclick="UI.openModalFromURL('/users/edit/1', '/users', '341eb7ed')" class="link-unstyled"><i class="fas fa-edit"></i></a>
```

HREF seems to take precedence. After removing it, the modal window is shown.

**Comment by iglocska** [comment]
Thanks, indeed, that was due to some over-eager baseurl prepending
