### ISSUE TITLE
How to change mail address of default admin user?

### ISSUE THREAD

**Issue by wagner-certat** [cerebrate-project/cerebrate#47]
The default user (ID 1, name admin) has the e-mail address `admin@admin.test`. How can we change that to an existing internal address? The user edit window does not allow to change it.

**Comment by iglocska** [comment]
This is correct. User accounts are tied to individuals, so you'd have to update the individual or associate the user with a new individual.

**Comment by wagner-certat** [comment]
Ah, because of #44 I haven't found the option to do this :)
