### ISSUE TITLE
Login via API possible?

### ISSUE THREAD

**Issue by wagner-certat** [cerebrate-project/cerebrate#52]
Hi,

is there a way to login via some kind of API (which does not require a Browser or other logic to fulfil the CSRF token stuff) to do some basic monitoring of the Cerebrate "health"?

**Comment by mokaddem** [comment]
Hey,
Indeed, we were missing that.
It has been fixed on the develop branch in https://github.com/cerebrate-project/cerebrate/commit/1f8010a6ec278e6020f5479bd5ab526e2cbf2064

It allows using HTTP POST without requiring to have CSRF tokens.
HTTP GET should have worked nonetheless.

Similar to MISP, you have to pass the API key as an `Authorization` header.

Thanks for the heads up!

**Comment by wagner-certat** [comment]
Thanks, that works!
