### ISSUE TITLE
Import of "ENISA CSIRT inventory" fails with "Unkown template for UUID ..."

### ISSUE THREAD

**Issue by wagner-certat** [cerebrate-project/cerebrate#60]
#53 has been resolved, but now I have this:
```
sebastianw@cerebrate:~$ sudo -u www-data /var/www/cerebrate/bin/cake Importer --yes /var/www/cerebrate/config-enisa-csirts-inventory.json https://www.enisa.europa.eu/topics/csirts-in-europe/csirt-inventory/certs-by-country-interactive-map/tool_data.json
Unkown template for UUID 089c68c7-d97e-4f21-a798-159cd10f7864
```

Version v0.2-177-gf0f49ec

**Comment by mokaddem** [comment]
Is the template `089c68c7-d97e-4f21-a798-159cd10f7864` available in the `/metaTemplates/index`? If no, you probably have to load to the new template into the database. To do that, you have to click on `Update Meta Templates` on the side-panel.

**Comment by wagner-certat** [comment]
> Is the template `089c68c7-d97e-4f21-a798-159cd10f7864` available in the `/metaTemplates/index`?

This page showed an empty table.


> If no, you probably have to load to the new template into the database. To do that, you have to click on `Update Meta Templates` on the side-panel.

Results in a red box in the top right corner:

> There has been a problem with the operation
> Network response was not ok. ``

And no new entries in the error log. The response is status code 302, but otherwise completely empty.

After reloading the page I got green bars, one saying "4 templates updated."
Now the table has the 089c68c7-d97e-4f21-a798-159cd10f7864.

Thanks for your help!

However, then the Import results in tons of errors. As this is a different error, I opened #62

**Comment by mokaddem** [comment]
> Results in a red box in the top right corner:

Yeah this was a bug in the UI notification popup. It should be fixed now

> After reloading the page I got green bars, one saying "4 templates updated."

Cool!

> However, then the Import results in tons of errors. As this is a different error, I opened #62

Thanks, it's easier that way
