### ISSUE TITLE
Typo "unkown" -> "unknown"

### ISSUE THREAD

**Issue by wagner-certat** [cerebrate-project/cerebrate#71]
https://github.com/cerebrate-project/cerebrate/blob/611a0b490367b5d7d3e055cef27a78baf8ba5991/src/Command/ImporterCommand.php#L164

https://github.com/cerebrate-project/cerebrate/blob/611a0b490367b5d7d3e055cef27a78baf8ba5991/src/Command/ImporterCommand.php#L195

**Comment by adulau** [comment]
Thank you for the issue. It should be fixed.
